### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by orditeck** [rodrigocfd/react-app-state#1]
Using this package with React 16 breaks the callback.

Ref: https://github.com/rodrigocfd/react-app-state/blob/2c9d50ae20220f4e89058257912bb6be11b641eb/src/AppState.js#L82

See https://github.com/facebook/react/issues/10320

**Comment by orditeck** [comment]
Just sent a pull request. Tested & works great!

**Comment by rodrigocfd** [comment]
Merged, thanks man.

**Comment by orditeck** [comment]
I don't know how publishing package to npm works, but don't forget to create a new release on github & npm so I can update my dependency :) I also don't know if that's a breaking change, so IDK if 0.0.4 will work with React 15, I didn't try, if it doesn't work, I guess the version should be bumped to 0.1.0 instead of 0.0.4, I honestly don't know. Thanks!

**Comment by rodrigocfd** [comment]
@orditeck I just published it on NPM, see if it works for you.
